### ISSUE TITLE
Cannot find module 'jquery'

### ISSUE THREAD

**Issue by pfan8** [sunqibuhuake/atom-miku#1]
is there anything else I need to install? I have installed the editor atom only,it seems that there is no lib 'jquery'...

**Atom Version**: 1.3.2
**System**: Unknown Windows Version
**Thrown From**: [atom-miku](https://github.com/sunqibuhuake/atom-miku) package, v2.0.0
### Stack Trace

Failed to activate the atom-miku package

```
At Cannot find module 'jquery'

Error: Cannot find module 'jquery'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (C:\Users\admin\AppData\Local\atom\app-1.3.2\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (C:\Users\admin\AppData\Local\atom\app-1.3.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\admin\.atom\packages\atom-miku-master\lib\main.js:2:9)
    at Module._compile (C:\Users\admin\AppData\Local\atom\app-1.3.2\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\admin\AppData\Local\atom\app-1.3.2\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\admin\AppData\Local\atom\app-1.3.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\admin\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package.js:663:34)
    at Package.module.exports.Package.activateConfig (C:\Users\admin\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package.js:188:14)
    at Package.module.exports.Package.activateNow (C:\Users\admin\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package.js:166:14)
    at C:\Users\admin\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package.js:740:25
    at Emitter.module.exports.Emitter.emit (C:\Users\admin\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\admin\AppData\Local\atom\app-1.3.2\resources\app.asar\src\command-registry.js:241:20)
    at CommandRegistry.handleCommandEvent (C:\Users\admin\AppData\Local\atom\app-1.3.2\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\admin\AppData\Local\atom\app-1.3.2\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (C:\Users\admin\AppData\Local\atom\app-1.3.2\resources\app.asar\src\atom-environment.js:1016:28)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter.ipc.sendSync (C:\Users\admin\AppData\Local\atom\app-1.3.2\resources\atom.asar\renderer\api\lib\ipc.js:21:31)
    at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\admin\AppData\Local\atom\app-1.3.2\resources\atom.asar\renderer\api\lib\remote.js:143:29)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\admin\AppData\Local\atom\app-1.3.2\resources\app.asar\src\context-menu-manager.js:156:33)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentContextmenu (C:\Users\admin\AppData\Local\atom\app-1.3.2\resources\app.asar\src\window-event-handler.js:250:47)
    at HTMLDocument.<anonymous> (C:\Users\admin\AppData\Local\atom\app-1.3.2\resources\app.asar\src\window-event-handler.js:3:61)
```
### Commands

```
     -0:10.2.0 application:new-file (atom-text-editor.editor.is-focused)
  8x -0:07.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:02.2.0 AtomMiku:toggle (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
No installed packages

# Dev
No dev packages


```

**Comment by pfan8** [comment]
The error above is occured when installing package in local mode.
if I use native command to install it.There is annother error:

**Atom Version**: 1.3.2
**System**: Unknown Windows Version
**Thrown From**: [atom-miku](https://github.com/sunqibuhuake/atom-miku) package, v2.0.0

### Stack Trace

Uncaught TypeError: Cannot read property 'addFrame' of undefined

```
At C:\Users\admin\.atom\packages\atom-miku\lib\miku-view.js:108

TypeError: Cannot read property 'addFrame' of undefined
    at MikuView.module.exports.MikuView.addFrame (C:\Users\admin\.atom\packages\atom-miku\lib\miku-view.js:108:26)
    at C:\Users\admin\.atom\packages\atom-miku\lib\main.js:41:27
    at Emitter.module.exports.Emitter.emit (C:\Users\admin\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at C:\Users\admin\AppData\Local\atom\app-1.3.2\resources\app.asar\src\text-editor.js:210:32
    at Emitter.module.exports.Emitter.emit (C:\Users\admin\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at DisplayBuffer.module.exports.DisplayBuffer.emitDidChange (C:\Users\admin\AppData\Local\atom\app-1.3.2\resources\app.asar\src\display-buffer.js:313:20)
    at DisplayBuffer.module.exports.DisplayBuffer.updateScreenLines (C:\Users\admin\AppData\Local\atom\app-1.3.2\resources\app.asar\src\display-buffer.js:1224:19)
    at DisplayBuffer.module.exports.DisplayBuffer.handleTokenizedBufferChange (C:\Users\admin\AppData\Local\atom\app-1.3.2\resources\app.asar\src\display-buffer.js:1186:19)
    at C:\Users\admin\AppData\Local\atom\app-1.3.2\resources\app.asar\src\display-buffer.js:5:61
    at Emitter.module.exports.Emitter.emit (C:\Users\admin\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at TokenizedBuffer.module.exports.TokenizedBuffer.handleBufferChange (C:\Users\admin\AppData\Local\atom\app-1.3.2\resources\app.asar\src\tokenized-buffer.js:393:27)
    at C:\Users\admin\AppData\Local\atom\app-1.3.2\resources\app.asar\src\tokenized-buffer.js:69:24
    at Emitter.module.exports.Emitter.emit (C:\Users\admin\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at TextBuffer.module.exports.TextBuffer.applyChange (C:\Users\admin\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:664:27)
    at TextBuffer.module.exports.TextBuffer.revertToCheckpoint (C:\Users\admin\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:834:16)
    at TextBuffer.module.exports.TextBuffer.transact (C:\Users\admin\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:801:14)
    at TextEditor.module.exports.TextEditor.transact (C:\Users\admin\AppData\Local\atom\app-1.3.2\resources\app.asar\src\text-editor.js:1202:26)
    at C:\Users\admin\AppData\Local\atom\app-1.3.2\resources\app.asar\src\text-editor.js:796:24
    at TextEditor.module.exports.TextEditor.mergeSelections (C:\Users\admin\AppData\Local\atom\app-1.3.2\resources\app.asar\src\text-editor.js:2078:43)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (C:\Users\admin\AppData\Local\atom\app-1.3.2\resources\app.asar\src\text-editor.js:2044:35)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (C:\Users\admin\AppData\Local\atom\app-1.3.2\resources\app.asar\src\text-editor.js:794:19)
    at TextEditor.module.exports.TextEditor.insertText (C:\Users\admin\AppData\Local\atom\app-1.3.2\resources\app.asar\src\text-editor.js:760:19)
    at TextEditor.object.(anonymous function) [as insertText] (C:\Users\admin\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\underscore-plus\lib\underscore-plus.js:77:27)
    at TextEditorComponent.module.exports.TextEditorComponent.onTextInput (C:\Users\admin\AppData\Local\atom\app-1.3.2\resources\app.asar\src\text-editor-component.js:448:35)
    at HTMLDivElement.<anonymous> (C:\Users\admin\AppData\Local\atom\app-1.3.2\resources\app.asar\src\text-editor-component.js:3:61)
```

### Commands

```
     -8:54.4.0 application:new-file (atom-text-editor.editor.is-focused)
  8x -8:52 core:backspace (atom-text-editor.editor.is-focused)
     -8:46.4.0 AtomMiku:toggle (atom-text-editor.editor.is-focused)
     -0:53.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:27.9.0 application:new-file (div.panels)
     -0:25.9.0 AtomMiku:toggle (atom-text-editor.editor.is-focused)
```

### Config

``` json
{
  "core": {}
}
```

### Installed Packages

``` coffee
# User
atom-miku, v2.0.0

# Dev
No dev packages
```

**Comment by pfan8** [comment]
and my OS is cn_windows_10_multiple_editions_version_1511_x64

**Comment by sunqibuhuake** [comment]
I'll fix it tonight ╮(╯_╰)╭

**Comment by pfan8** [comment]
thx for paying attention to this issue,now it do not popup that error.However,there's nothing but a white panel to show.
It seems that the problem is the network,I found you use an outer link,then I tried  to view it,but failed.I remembered there are some limits connecting network in my working place,and I can use this plugin correctly at home.
So,there should be nothing to fix,or you can write a readme to remind others :)

**Comment by xmpxraw** [comment]
my OS is windows 10,and I have the same problem tonight , can not solve.if you can reply its how to solve ,I will be indebted forever,and  forgive my poor English.

**Comment by freenet-233** [comment]
yes,me too

**Comment by xmpxraw** [comment]
Just to try go to the project catalog and run this command: "npm install".

**Comment by xmpxraw** [comment]
大兄弟，试试跑下“ npm install ”

**Comment by DanceSmile** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.12.7
**Electron Version**: 1.3.13
**System**: Unknown Windows Version
**Thrown From**: [atom-miku](https://github.com/sunqibuhuake/atom-miku) package, v2.2.5


### Stack Trace

Failed to activate the atom-miku package

```
At url.indexOf is not a function

TypeError: url.indexOf is not a function
    at jQuery.fn.load (C:\Users\siyue\.atom\packages\atom-miku\node_modules\jquery\dist\jquery.js:9793:13)
    at MikuView.module.exports.MikuView.initEventBind (C:\Users\siyue\.atom\packages\atom-miku\lib\miku-view.js:106:21)
    at Object.activate (C:\Users\siyue\.atom\packages\atom-miku\lib\main.js:21:23)
    at Package.module.exports.Package.activateNow (C:\Users\siyue\AppData\Local\atom\app-1.12.7\resources\app.asar\src\package.js:184:19)
    at C:\Users\siyue\AppData\Local\atom\app-1.12.7\resources\app.asar\src\package.js:827:25
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\siyue\AppData\Local\atom\app-1.12.7\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\siyue\AppData\Local\atom\app-1.12.7\resources\app.asar\node_modules\event-kit\lib\emitter.js:129:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\siyue\AppData\Local\atom\app-1.12.7\resources\app.asar\src\command-registry.js:240:20)
    at C:\Users\siyue\AppData\Local\atom\app-1.12.7\resources\app.asar\src\command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\siyue\AppData\Local\atom\app-1.12.7\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:587:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\siyue\AppData\Local\atom\app-1.12.7\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:382:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\siyue\AppData\Local\atom\app-1.12.7\resources\app.asar\src\window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (C:\Users\siyue\AppData\Local\atom\app-1.12.7\resources\app.asar\src\window-event-handler.js:3:59)
```

### Commands

```
     -5:52 editor:newline (atom-text-editor.editor.is-focused)
     -5:51.9.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -5:51.9.0 editor:newline (atom-text-editor.editor.is-focused)
  3x -5:51.6.0 core:move-up (atom-text-editor.editor.is-focused)
     -5:50.4.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -5:50.4.0 editor:newline (atom-text-editor.editor.is-focused)
  5x -5:49 core:backspace (atom-text-editor.editor.is-focused)
     -5:46.8.0 AtomMiku:toggle (atom-text-editor.editor.is-focused)
     -5:28.7.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -2:07.8.0 AtomMiku:toggle (div.terminal)
  2x -2:04.9.0 editor:delete-line (div.terminal)
     -1:57.7.0 core:undo (atom-text-editor.editor.is-focused)
  6x -1:57.2.0 core:move-up (atom-text-editor.editor.is-focused)
  3x -1:55.2.0 AtomMiku:toggle (atom-text-editor.editor.is-focused)
  2x -1:52.9.0 editor:delete-line (atom-text-editor.editor.is-focused)
     -0:03.1.0 AtomMiku:toggle (button.btn.icon.enablement.icon-playback-pause)
```

### Config

```json
{
  "core": {
    "telemetryConsent": "limited"
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v1.1.0 (active)
atom-ctags, v5.0.0 (active)
atom-miku, v2.2.5 (inactive)
docblockr, v0.9.1 (active)
file-icons, v1.7.25 (active)
git-control, v0.8.2 (inactive)
git-plus, v6.3.0 (active)
minimap, v4.25.7 (active)
platformio-ide-terminal, v2.2.2 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (active)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (active)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```
