### ISSUE TITLE
error ctl+alt+k in mac os 10.11.3 

### ISSUE THREAD

**Issue by blueskymana** [sunqibuhuake/atom-miku#16]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.2
**System**: Mac OS X 10.11.3
**Thrown From**: [atom-miku](https://github.com/sunqibuhuake/atom-miku) package, v2.2.5
### Stack Trace

Failed to activate the atom-miku package

```
At Cannot read property 'onDidChange' of undefined

TypeError: Cannot read property 'onDidChange' of undefined
    at Object.module.exports.AtomMiku.activate (/Users/Arslan/.atom/packages/atom-miku/lib/main.js:40:29)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:795:25
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -0:55.2.0 settings-view:open (ul.list-inline.tab-bar.inset-panel)
     -0:47.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.2.0 AtomMiku:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
atom-miku, v2.2.5

# Dev
No dev packages
```

**Comment by OnionStu** [comment]
cd <package path> 
npm i
