### ISSUE TITLE
url.indexOf is not a function

### ISSUE THREAD

**Issue by xiaozhaoosc** [sunqibuhuake/atom-miku#20]
at [object Object].jQuery.fn.load (C:\Users\user.atom\packages\atom-miku\node_modules\jquery\dist\jquery.js:9612:13)
    at MikuView.module.exports.MikuView.initEventBind (C:\Users\user.atom\packages\atom-miku\lib\miku-view.js:106:21)
    at Object.module.exports.AtomMiku.activate (C:\Users\user.atom\packages\atom-miku\lib\main.js:21:23)
    at Package.module.exports.Package.activateNow (C:\Users\user\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:183:20)
    at C:\Users\user\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:795:25
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\user\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\user\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\user\AppData\Local\atom\app-1.8.0\resources\app.asar\src\command-registry.js:241:20)
    at C:\Users\user\AppData\Local\atom\app-1.8.0\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\user\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\user\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\user\AppData\Local\atom\app-1.8.0\resources\app.asar\src\window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (C:\Users\user\AppData\Local\atom\app-1.8.0\resources\app.asar\src\window-event-handler.js:3:61)

**Comment by EdifierCN** [comment]
同上

**Comment by xiaozhuai** [comment]
```
TypeError: url.indexOf is not a function
    at jQuery.fn.load (/Users/xiaozhuai/.atom/packages/atom-miku/node_modules/jquery/dist/jquery.js:9649:13)
    at MikuView.module.exports.MikuView.initEventBind (/Users/xiaozhuai/.atom/packages/atom-miku/lib/miku-view.js:106:21)
    at Object.module.exports.AtomMiku.activate (/Users/xiaozhuai/.atom/packages/atom-miku/lib/main.js:21:23)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:798:25
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:20)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1109:28)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:329:25)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
```

同样的问题

**Comment by yfd0101** [comment]
换个jQuery库，不要用3.1.0版本的jQuery，换成老版本的就可以运行了，比如，我用的JQuery2.2.0，并且你必须把把他改成JQuery,js，不然会提示找不到JQuery模块。
路径是：C:\Users\yourname\\.atom\packages\atom-miku\node_modules\jquery\dist\JQuery.js
（You can replace the JQuery3.x.0 with  a older JQuery.js！For example ,I use the JQuery2.2.0,and you must rename the JQuey2.2.0.js to JQuery.js,）

**Comment by ryanypm** [comment]
![image](https://cloud.githubusercontent.com/assets/7519919/18416177/f7a8a700-783e-11e6-933c-05c2562db03d.png)
mike-view.js

**Comment by cjguo1988** [comment]
@yfd0101 👍  thank u, it works on win10!

**Comment by lvanas** [comment]
win10 为什么替换为 JQuery2.2.0 后，不报错了，但是只有音乐，没有人物呢？  大神还在嘛，求解答。。@yfd0101

**Comment by FeDemo** [comment]
@yfd0101 thank,我这边也是这问题.换了个jquery后解决了
