### ISSUE TITLE
Failed to activate the atom-miku package

### ISSUE THREAD

**Issue by ghost** [sunqibuhuake/atom-miku#29]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.2 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [atom-miku](https://github.com/sunqibuhuake/atom-miku) package 2.2.5

### Stack Trace

Failed to activate the atom-miku package

```
At url.indexOf is not a function

TypeError: url.indexOf is not a function
    at jQuery.fn.init.jQuery.fn.load (/packages/atom-miku/node_modules/jquery/dist/jquery.js:9823:13)
    at MikuView.module.exports.MikuView.initEventBind (/packages/atom-miku/lib/miku-view.js:106:21)
    at Object.activate (/packages/atom-miku/lib/main.js:21:23)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:253:25)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:984:31
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:353:24)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -0:54.3.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling)
     -0:07.7.0 AtomMiku:toggle (input.hidden-input)
```

### Non-Core Packages

```
angularjs 0.4.0 
atom-beautify 0.30.6 
atom-bootstrap3 1.2.12 
atom-miku 2.2.5 
atom-simplified-chinese-menu 0.6.5 
atom-ternjs 0.18.3 
atom-typescript 11.0.10 
autocomplete-modules 1.7.3 
autoprefixer 3.7.1 
color-picker 2.2.5 
file-icons 2.1.13 
highlight-selected 0.13.1 
jsformat 0.9.3 
jslint 1.5.1 
language-vue 0.23.1 
language-vue-component 0.5.0 
linter 2.2.0 
linter-csslint 2.0.0 
linter-eslint 8.4.0 
linter-jslint 11.1.0 
minimap 4.29.7 
node-debugger 1.10.1 
regex-railroad-diagram 0.19.4 
seti-ui 1.9.0 
```

**Comment by iMactool** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [atom-miku](https://github.com/sunqibuhuake/atom-miku) package 2.2.5


### Stack Trace

Failed to activate the atom-miku package

```
At url.indexOf is not a function

TypeError: url.indexOf is not a function
    at jQuery.fn.init.jQuery.fn.load (/packages/atom-miku/node_modules/jquery/dist/jquery.js:9823:13)
    at MikuView.module.exports.MikuView.initEventBind (/packages/atom-miku/lib/miku-view.js:106:21)
    at Object.activate (/packages/atom-miku/lib/main.js:21:23)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:253:25)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:984:31
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:353:24)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
  4x -3:33.1.0 core:confirm (input.hidden-input)
  3x -1:13.3.0 core:backspace (input.hidden-input)
  5x -1:12.3.0 editor:newline (input.hidden-input)
     -1:09.1.0 autocomplete-plus:confirm (input.hidden-input)
  2x -1:09.0 editor:newline (input.hidden-input)
  3x -1:08.7.0 autocomplete-plus:confirm (input.hidden-input)
  3x -1:08.2.0 editor:newline (input.hidden-input)
  4x -1:07.7.0 autocomplete-plus:confirm (input.hidden-input)
  5x -1:05.3.0 editor:newline (input.hidden-input)
     -0:38.2.0 AtomMiku:toggle (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.6.0 
atom-miku 2.2.5 
es6-javascript 1.0.0 
language-vue 0.23.1 
vue-autocomplete 0.1.1 
vue2-autocomplete 0.1.0-alpha.4 
```

**Comment by lizhihao6** [comment]
Fix that.
这个错误是由于JQuery升级到3.0.0后类型错误

把/.atom/packages/atom-miku/lib/miku-view.js 106行代码里调用load函数的方式
that.iframe.onload(function(){
改为
that.iframe.on('load',function() {
就好了

**Comment by Twor** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: [atom-miku](https://github.com/sunqibuhuake/atom-miku) package 2.2.5


### Stack Trace

Failed to activate the atom-miku package

```
At url.indexOf is not a function

TypeError: url.indexOf is not a function
    at jQuery.fn.init.jQuery.fn.load (/packages/atom-miku-diy/node_modules/jquery/dist/jquery.js:9857:13)
    at MikuView.module.exports.MikuView.initEventBind (/packages/atom-miku/lib/miku-view.js:106:21)
    at Object.activate (/packages/atom-miku/lib/main.js:21:23)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.23.3/resources/app/src/package.js:255:25)
    at ~/AppData/Local/atom/app-1.23.3/resources/app/src/package.js:1022:31
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.23.3/resources/app/src/command-registry.js:360:24)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.23.3/resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (~/AppData/Local/atom/app-1.23.3/resources/app/src/atom-environment.js:1393:34)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.23.3/resources/app/src/application-delegate.js:335:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:13 core:save (input.hidden-input)
     -0:09.8.0 AtomMiku:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-miku 2.2.5 
autocomplete-paths 2.12.2 
browser-plus 0.0.98 
emmet 2.4.3 
file-icons 2.1.16 
linter 2.2.0 
linter-php 1.5.1 
simplified-chinese-menu 5.3.5 
```

**Comment by song872229436** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.1 x64
**Electron**: 1.7.11
**OS**: Unknown Windows version
**Thrown From**: [atom-miku](https://github.com/sunqibuhuake/atom-miku) package 2.2.5


### Stack Trace

Failed to activate the atom-miku package

```
At url.indexOf is not a function

TypeError: url.indexOf is not a function
    at jQuery.fn.init.jQuery.fn.load (/packages/atom-miku/node_modules/jquery/dist/jquery.js:9857:13)
    at MikuView.module.exports.MikuView.initEventBind (/packages/atom-miku/lib/miku-view.js:106:21)
    at Object.activate (/packages/atom-miku/lib/main.js:21:23)
    at Package.activateNow (~/AppData/Local/atom/app-1.25.1/resources/app/src/package.js:230:33)
    at activationCommandSubscriptions.add.commandRegistry.onWillDispatch.event (~/AppData/Local/atom/app-1.25.1/resources/app/src/package.js:865:28)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.25.1/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.25.1/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.25.1/resources/app/src/command-registry.js:360:24)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.25.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.25.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.25.1/resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
     -7:59.3.0 core:backspace (input.hidden-input)
     -7:57.9.0 AtomMiku:toggle (input.hidden-input)
 17x -6:23.7.0 core:backspace (input.hidden-input)
     -6:22 core:undo (input.hidden-input)
 15x -6:21 core:backspace (input.hidden-input)
     -6:18.7.0 core:undo (input.hidden-input)
  5x -6:18.3.0 core:backspace (input.hidden-input)
     -6:16.8.0 core:undo (input.hidden-input)
  4x -6:16.3.0 core:backspace (input.hidden-input)
  6x -6:15.2.0 core:move-left (input.hidden-input)
  6x -6:12.7.0 core:backspace (input.hidden-input)
     -6:10.2.0 autocomplete-plus:confirm (input.hidden-input)
     -6:09.4.0 core:undo (input.hidden-input)
     -6:08.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-chs-menu 1.0.0 
atom-miku 2.2.5 
simplified-chinese-menu 5.3.5 
```

**Comment by hiroki001** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.26.1 x64
**Electron**: 1.7.11
**OS**: Unknown Windows version
**Thrown From**: [atom-miku](https://github.com/sunqibuhuake/atom-miku) package 2.2.5


### Stack Trace

Failed to activate the atom-miku package

```
At Cannot read property 'onDidChange' of undefined

TypeError: Cannot read property 'onDidChange' of undefined
    at Object.activate (/packages/atom-miku/lib/main.js:40:29)
    at Package.activateNow (~/AppData/Local/atom/app-1.26.1/resources/app/src/package.js:230:33)
    at activationCommandSubscriptions.add.commandRegistry.onWillDispatch.event (~/AppData/Local/atom/app-1.26.1/resources/app/src/package.js:865:28)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.26.1/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.26.1/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.26.1/resources/app/src/command-registry.js:360:24)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.26.1/resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.dispatchApplicationMenuCommand (~/AppData/Local/atom/app-1.26.1/resources/app/src/atom-environment.js:1347:25)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.26.1/resources/app/src/application-delegate.js:339:53)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:197:7)
```

### Commands

```
     -0:23.8.0 AtomMiku:toggle (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
atom-miku 2.2.5 
power-effects 0.4.0 
simplified-chinese-menu 5.3.5 
```

**Comment by hiroki001** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.26.1 x64
**Electron**: 1.7.11
**OS**: Unknown Windows version
**Thrown From**: [atom-miku](https://github.com/sunqibuhuake/atom-miku) package 2.2.5


### Stack Trace

Failed to activate the atom-miku package

```
At url.indexOf is not a function

TypeError: url.indexOf is not a function
    at jQuery.fn.init.jQuery.fn.load (/packages/atom-miku/node_modules/jquery/dist/jquery.js:9857:13)
    at MikuView.module.exports.MikuView.initEventBind (/packages/atom-miku/lib/miku-view.js:106:21)
    at Object.activate (/packages/atom-miku/lib/main.js:21:23)
    at Package.activateNow (~/AppData/Local/atom/app-1.26.1/resources/app/src/package.js:230:33)
    at activationCommandSubscriptions.add.commandRegistry.onWillDispatch.event (~/AppData/Local/atom/app-1.26.1/resources/app/src/package.js:865:28)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.26.1/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.26.1/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.26.1/resources/app/src/command-registry.js:360:24)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.26.1/resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.dispatchApplicationMenuCommand (~/AppData/Local/atom/app-1.26.1/resources/app/src/atom-environment.js:1347:25)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.26.1/resources/app/src/application-delegate.js:339:53)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:197:7)
```

### Commands

```
     -0:04.8.0 AtomMiku:toggle (atom-pane.pane.active)
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
atom-miku 2.2.5 
power-effects 0.4.0 
simplified-chinese-menu 5.3.5 
```

**Comment by acgavalon** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.31.2 x64
**Electron**: 2.0.7
**OS**: Unknown Windows version
**Thrown From**: [atom-miku](https://github.com/sunqibuhuake/atom-miku) package 2.2.5


### Stack Trace

Failed to activate the atom-miku package

```
At Cannot find module 'jquery'

Error: Cannot find module 'jquery'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.31.2/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.31.2/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.31.2/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-miku/lib/main.js:2:9)
    at /packages/atom-miku/lib/main.js:84:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.31.2/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.31.2/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (~/AppData/Local/atom/app-1.31.2/resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.31.2/resources/app/src/package.js:782:33)
    at Package.activateNow (~/AppData/Local/atom/app-1.31.2/resources/app/src/package.js:220:40)
    at activationCommandSubscriptions.add.commandRegistry.onWillDispatch.event (~/AppData/Local/atom/app-1.31.2/resources/app/src/package.js:865:28)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.31.2/resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.31.2/resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.31.2/resources/app/src/command-registry.js:360:24)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.31.2/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.31.2/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.31.2/resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
     -0:19.8.0 AtomMiku:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-miku 2.2.5 
atom-ternjs 0.18.3 
busy-signal 1.4.3 
intentions 1.1.5 
linter 2.2.0 
linter-eslint 8.4.1 
linter-ui-default 1.7.1 
simplified-chinese-menu 5.3.5 
```

**Comment by censujiang** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.28.0-beta3 ia32
**Electron**: 2.0.1
**OS**: Unknown Windows version
**Thrown From**: [atom-miku](https://github.com/sunqibuhuake/atom-miku) package 2.2.5


### Stack Trace

Failed to activate the atom-miku package

```
At url.indexOf is not a function

TypeError: url.indexOf is not a function
    at jQuery.fn.init.jQuery.fn.load (/packages/atom-miku/node_modules/jquery/dist/jquery.js:9857:13)
    at MikuView.module.exports.MikuView.initEventBind (/packages/atom-miku/lib/miku-view.js:106:21)
    at Object.activate (/packages/atom-miku/lib/main.js:21:23)
    at Package.activateNow (D:/atombianjiqi-v1.28.0b3/Atom Beta/resources/app/src/package.js:230:33)
    at activationCommandSubscriptions.add.commandRegistry.onWillDispatch.event (D:/atombianjiqi-v1.28.0b3/Atom Beta/resources/app/src/package.js:865:28)
    at Function.module.exports.Emitter.simpleDispatch (D:/atombianjiqi-v1.28.0b3/Atom Beta/resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (D:/atombianjiqi-v1.28.0b3/Atom Beta/resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at CommandRegistry.handleCommandEvent (D:/atombianjiqi-v1.28.0b3/Atom Beta/resources/app/src/command-registry.js:360:24)
    at CommandRegistry.dispatch (D:/atombianjiqi-v1.28.0b3/Atom Beta/resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.dispatchContextMenuCommand (D:/atombianjiqi-v1.28.0b3/Atom Beta/resources/app/src/atom-environment.js:1351:25)
    at EventEmitter.outerCallback (D:/atombianjiqi-v1.28.0b3/Atom Beta/resources/app/src/application-delegate.js:346:53)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
```

### Commands

```
     -4:57.1.0 application:add-project-folder (atom-pane.pane.active)
  2x -3:39.5.0 core:save (input.hidden-input)
     -3:34.1.0 find-and-replace:show (input.hidden-input)
     -3:20.1.0 core:copy (span.syntax--string.syntax--quoted.syntax--double.syntax--html)
     -3:17.4.0 core:paste (div.placeholder-text)
  3x -3:14.7.0 editor:newline (input.hidden-input)
  2x -3:12.5.0 core:undo (input.hidden-input)
     -3:07.3.0 core:confirm (input.hidden-input)
     -2:59.4.0 core:copy (span.syntax--string.syntax--quoted.syntax--double.syntax--html)
     -2:56.7.0 core:paste (input.hidden-input)
  2x -2:55.7.0 core:confirm (input.hidden-input)
     -1:06.7.0 AtomMiku:toggle (div.line)
     -0:36.9.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
advanced-open-file 0.16.8 
apicloud 0.2.0 
apicloud-autocomplete 0.0.2 
atom-beautify 0.33.4 
atom-html-preview 0.2.6 
atom-miku 2.2.5 
atom-minify 0.8.0 
autocomplete-paths 2.12.2 
browser-plus 0.0.98 
color-picker 2.3.0 
file-icons 2.1.29 
git-log 0.4.1 
language-javascript-jsx 0.3.7 
last-cursor-position 0.9.3 
minimap 4.29.9 
open-in-browsers 0.0.30 
platformio-ide-terminal 2.9.0 
quick-highlight 0.13.0 
script 3.18.1 
simplified-chinese-menu 5.3.5 
```
