### ISSUE TITLE
为什么没有音乐??到底有没有?

### ISSUE THREAD

**Issue by binbinshan** [sunqibuhuake/atom-miku#30]
我集成后,发现报错,然后按照方法替换了jquery,可是没有音乐额..jquery换成了v2.1.4 版本

**Comment by Twor** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: [atom-miku](https://github.com/sunqibuhuake/atom-miku) package 2.2.5


### Stack Trace

Failed to activate the atom-miku package

```
At url.indexOf is not a function

TypeError: url.indexOf is not a function
    at jQuery.fn.init.jQuery.fn.load (/packages/atom-miku-diy/node_modules/jquery/dist/jquery.js:9857:13)
    at MikuView.module.exports.MikuView.initEventBind (/packages/atom-miku/lib/miku-view.js:106:21)
    at Object.activate (/packages/atom-miku/lib/main.js:21:23)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.23.3/resources/app/src/package.js:255:25)
    at ~/AppData/Local/atom/app-1.23.3/resources/app/src/package.js:1022:31
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.23.3/resources/app/src/command-registry.js:360:24)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.23.3/resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (~/AppData/Local/atom/app-1.23.3/resources/app/src/atom-environment.js:1393:34)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.23.3/resources/app/src/application-delegate.js:335:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:13 core:save (input.hidden-input)
     -0:09.8.0 AtomMiku:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-miku 2.2.5 
autocomplete-paths 2.12.2 
browser-plus 0.0.98 
emmet 2.4.3 
file-icons 2.1.16 
linter 2.2.0 
linter-php 1.5.1 
simplified-chinese-menu 5.3.5 
```
