### ISSUE TITLE
Failed to activate the atom-miku package

### ISSUE THREAD

**Issue by bluse** [sunqibuhuake/atom-miku#6]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.3.3
**System**: Mac OS X 10.10.3
**Thrown From**: [atom-miku](https://github.com/sunqibuhuake/atom-miku) package, v2.2.5
### Stack Trace

Failed to activate the atom-miku package

```
At Cannot read property 'onDidChange' of undefined

TypeError: Cannot read property 'onDidChange' of undefined
    at Object.module.exports.AtomMiku.activate (/Users/bluse/.atom/packages/atom-miku/lib/main.js:40:29)
    at Package.module.exports.Package.activateNow (/Users/bluse/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:170:19)
    at /Users/bluse/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:740:25
    at Function.module.exports.Emitter.simpleDispatch (/Users/bluse/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Users/bluse/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/bluse/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:20)
    at /Users/bluse/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Users/bluse/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Users/bluse/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Users/bluse/Downloads/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Users/bluse/Downloads/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -4:08.2.0 tool-panel:unfocus (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -3:44.4.0 find-and-replace:show (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -3:41.9.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -3:41.9.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -2:52.3.0 project-find:show (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -2:36.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:32.1.0 core:close (ol.results-view.list-tree.focusable-panel.has-collapsable-children)
  2x -2:08.8.0 core:undo (atom-text-editor.editor.is-focused)
     -1:59.2.0 settings-view:open (atom-text-editor.editor.is-focused)
     -1:43.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:02.0 AtomMiku:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
atom-miku, v2.2.5

# Dev
No dev packages
```

**Comment by justrustc** [comment]
I have the same problem.
OS:win10

**Comment by bluse** [comment]
I restart the system, and then solve this problem

**Comment by justrustc** [comment]
@bluse thanks

**Comment by smancang** [comment]
这是因为当前没有active的页签 所以失败 ，重启atom，随便打开个文件，再ctrl+alt+k 就不会出错了
This is because there is no active tab.Restart atom,open a file any one you like,then press ctrl+alt +k, it works.

**Comment by littledogboy** [comment]
楼上正解

**Comment by xmpxraw** [comment]
I have the same problem,so trouble.

**Comment by BJming** [comment]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.8.0
**System**: elementary OS
**Thrown From**: [atom-miku](https://github.com/sunqibuhuake/atom-miku) package, v2.2.5

### Stack Trace

Failed to activate the atom-miku package

```
At url.indexOf is not a function

TypeError: url.indexOf is not a function
    at [object Object].jQuery.fn.load (/home/bjming/.atom/packages/atom-miku/node_modules/jquery/dist/jquery.js:9649:13)
    at MikuView.module.exports.MikuView.initEventBind (/home/bjming/.atom/packages/atom-miku/lib/miku-view.js:106:21)
    at Object.module.exports.AtomMiku.activate (/home/bjming/.atom/packages/atom-miku/lib/main.js:21:23)
    at Package.module.exports.Package.activateNow (/opt/atom/resources/app.asar/src/package.js:183:20)
    at /opt/atom/resources/app.asar/src/package.js:795:25
    at Function.module.exports.Emitter.simpleDispatch (/opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:241:20)
    at CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/opt/atom/resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/opt/atom/resources/app.asar/src/atom-environment.js:1100:28)
    at EventEmitter.outerCallback (/opt/atom/resources/app.asar/src/application-delegate.js:327:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```

### Commands

```
     -0:03.7.0 AtomMiku:toggle (atom-text-editor.editor.is-focused.power-mode)
```

### Config

``` json
{}
```

### Installed Packages

``` coffee
# User
activate-power-mode, v0.7.0
atom-miku, v2.2.5
minimap, v4.24.7

# Dev
No dev packages
```

**Comment by xiaozhuai** [comment]
```
TypeError: url.indexOf is not a function
    at jQuery.fn.load (/Users/xiaozhuai/.atom/packages/atom-miku/node_modules/jquery/dist/jquery.js:9649:13)
    at MikuView.module.exports.MikuView.initEventBind (/Users/xiaozhuai/.atom/packages/atom-miku/lib/miku-view.js:106:21)
    at Object.module.exports.AtomMiku.activate (/Users/xiaozhuai/.atom/packages/atom-miku/lib/main.js:21:23)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:798:25
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:20)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1109:28)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:329:25)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
```

**Comment by liuchangxing** [comment]
可以关了声音吗？？？？

**Comment by tempest2023** [comment]
The error url.indexOf is not a function
I think it is due to different jquery.js version.
Try to replace jquery2.X.0.js with jquery3.X.0.js and restart atom
